### ISSUE TITLE
Not compile in VS 2019. 

### ISSUE THREAD

**Issue by AutoDolor** [DaveDubUK/bvhacker#1]
I dont know what SDK use you for compile this, but I give error in solution and vsxproj...  (The solver for "this a Mac format" I notice in your "google" forum, about the limit of 2084 characters for line. Thanks for listen me.  But, all around, the code in VS 2019 dont compile rigth..

**Comment by DaveDubUK** [comment]
Hi,

Funnily enough, I compiled it using VS2019 just last week when I updated a
few things.

The github is updated:  https://github.com/DaveDubUK/bvhacker

Note it compiles for 32-bit. I've not sorted it to compile on 64-bit.

 - Dave
