### ISSUE TITLE
Some BVH File cant set to T-POSE

### ISSUE THREAD

**Issue by ag2s20150909** [DaveDubUK/bvhacker#2]
[Olivia_Pleased-BVH.zip](https://github.com/DaveDubUK/bvhacker/files/5049038/Olivia_Pleased-BVH.zip)

**Comment by DaveDubUK** [comment]
When Set T Stance is used, bvhacker simply adds a new frame at the start of the animation and sets zero rotation on every joint for this frame. The pose that the figure takes when every joint's rotation is set to zero depends on how the skeleton was originally built.

In the case of the Second Life (non-Bento) skeleton, setting every joint's rotation to zero puts the figure in a T Stance. This is also the case for many (but not all) skeletons.

In the case of your file, when every joint's rotation is set to zero, the pose you see in bvhacker is the expected result. You can verify this by selecting joints and looking at the rotation values before and after using Set T Stance.
