### ISSUE TITLE
Problem for parts

### ISSUE THREAD

**Issue by m-asyua** [DaveDubUK/bvhacker#3]
![trouble](https://user-images.githubusercontent.com/83494645/143513927-3afa11ee-7061-41fd-84c5-ea537fb51cfc.png)

I use Version 1.9.1, Windows 10, I can not see each part exactly. (Buttons and Sliders are OK and I can edit it.)

**Comment by DaveDubUK** [comment]
It looks like your character is very small 

Have a look at the Figure Height in the File Properties section on the bottom left panel.
bvhacker expects the bvh file units to be cm

Try scaling it up from the edit menu

**Comment by m-asyua** [comment]
I tried scaling my character up from the menu (Scale up), and then I can see parts exactly.
Thank you very much for your answer.
